# Generated by Django 5.0 on 2023-12-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('b', 'bend'), ('h', 'hitch'), ('l', 'loop'), ('o', 'other'), ('s', 'stopper')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='knot',
            name='type',
        ),
    ]
