# Generated by Django 5.0 on 2023-12-13 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_type_remove_knot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='knot',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('b', 'bend'), ('h', 'hitch'), ('l', 'loop'), ('o', 'other'), ('s', 'stopper')], default='o', max_length=1),
        ),
    ]
